version: '3.8'

services:
  glance:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./glance.yml:/app/config/glance.yml
    restart: unless-stopped
    environment:
      - PORT=8080 